import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/contact_submission_model.dart';

class ContactSubmissionService extends ChangeNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  
  List<ContactSubmission> _submissions = [];
  bool _isLoading = false;
  String _searchQuery = '';
  ContactStatus? _selectedStatus;

  List<ContactSubmission> get submissions => _submissions;
  bool get isLoading => _isLoading;
  String get searchQuery => _searchQuery;
  ContactStatus? get selectedStatus => _selectedStatus;

  Future<void> loadSubmissions() async {
    _isLoading = true;
    notifyListeners();

    try {
      final querySnapshot = await _firestore
          .collection('contact_submissions')
          .orderBy('submittedAt', descending: true)
          .get();

      _submissions = querySnapshot.docs
          .map((doc) => ContactSubmission.fromFirestore(doc))
          .toList();

      debugPrint('Loaded ${_submissions.length} contact submissions');
    } catch (e) {
      debugPrint('Error loading contact submissions: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<String> submitContactForm({
    required String name,
    required String email,
    required String subject,
    required String message,
  }) async {
    try {
      final submission = ContactSubmission(
        id: '', // Will be generated by Firestore
        name: name,
        email: email,
        subject: subject,
        message: message,
        submittedAt: DateTime.now(),
      );

      final docRef = await _firestore
          .collection('contact_submissions')
          .add(submission.toFirestore());

      debugPrint('Contact form submitted with ID: ${docRef.id}');
      await loadSubmissions(); // Refresh the list
      return docRef.id;
    } catch (e) {
      debugPrint('Error submitting contact form: $e');
      rethrow;
    }
  }

  Future<void> updateSubmissionStatus(
    String submissionId,
    ContactStatus status, {
    String? adminNotes,
    String? resolvedBy,
  }) async {
    try {
      final updates = {
        'status': status.toString().split('.').last,
        'updatedAt': Timestamp.fromDate(DateTime.now()),
      };

      if (adminNotes != null) {
        updates['adminNotes'] = adminNotes;
      }

      if (resolvedBy != null) {
        updates['resolvedBy'] = resolvedBy;
        if (status == ContactStatus.resolved || status == ContactStatus.closed) {
          updates['resolvedAt'] = Timestamp.fromDate(DateTime.now());
        }
      }

      await _firestore
          .collection('contact_submissions')
          .doc(submissionId)
          .update(updates);

      debugPrint('Contact submission $submissionId status updated to $status');
      await loadSubmissions(); // Refresh the list
    } catch (e) {
      debugPrint('Error updating contact submission status: $e');
      rethrow;
    }
  }

  void searchSubmissions(String query) {
    _searchQuery = query.toLowerCase();
    notifyListeners();
  }

  void filterByStatus(ContactStatus? status) {
    _selectedStatus = status;
    notifyListeners();
  }

  List<ContactSubmission> get filteredSubmissions {
    List<ContactSubmission> filtered = List.from(_submissions);

    // Apply search filter
    if (_searchQuery.isNotEmpty) {
      filtered = filtered.where((submission) {
        return submission.name.toLowerCase().contains(_searchQuery) ||
               submission.email.toLowerCase().contains(_searchQuery) ||
               submission.subject.toLowerCase().contains(_searchQuery) ||
               submission.message.toLowerCase().contains(_searchQuery);
      }).toList();
    }

    // Apply status filter
    if (_selectedStatus != null) {
      filtered = filtered.where((submission) => submission.status == _selectedStatus).toList();
    }

    return filtered;
  }

  void clearFilters() {
    _searchQuery = '';
    _selectedStatus = null;
    notifyListeners();
  }

  // Get statistics
  Map<String, int> getSubmissionStatistics() {
    final stats = <String, int>{};
    
    for (final status in ContactStatus.values) {
      stats[status.toString().split('.').last] = 
          _submissions.where((submission) => submission.status == status).length;
    }
    
    return stats;
  }

  // Get recent submissions (last 7 days)
  List<ContactSubmission> getRecentSubmissions() {
    final sevenDaysAgo = DateTime.now().subtract(const Duration(days: 7));
    return _submissions.where((submission) => submission.submittedAt.isAfter(sevenDaysAgo)).toList();
  }
}
