// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGSgI0PA8IyfcOecVymqj8DM2qQIVjl8E',
    appId: '1:15635707090:web:fba03a67ceb2f43241290b',
    messagingSenderId: '15635707090',
    projectId: 'petcare-3f9cb',
    authDomain: 'petcare-3f9cb.firebaseapp.com',
    storageBucket: 'petcare-3f9cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQuy_Zwbfp4tqgwRSfQLlEKFn2yH_AZ9c',
    appId: '1:15635707090:android:8b2118cab0b6362241290b',
    messagingSenderId: '15635707090',
    projectId: 'petcare-3f9cb',
    storageBucket: 'petcare-3f9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJot4paYY9rmKMOi4pLqzpssvvDDXMJ0M',
    appId: '1:15635707090:ios:6d7f7d421d0e78e141290b',
    messagingSenderId: '15635707090',
    projectId: 'petcare-3f9cb',
    storageBucket: 'petcare-3f9cb.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJot4paYY9rmKMOi4pLqzpssvvDDXMJ0M',
    appId: '1:15635707090:ios:6d7f7d421d0e78e141290b',
    messagingSenderId: '15635707090',
    projectId: 'petcare-3f9cb',
    storageBucket: 'petcare-3f9cb.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGSgI0PA8IyfcOecVymqj8DM2qQIVjl8E',
    appId: '1:15635707090:web:3bb38cd55bbde6eb41290b',
    messagingSenderId: '15635707090',
    projectId: 'petcare-3f9cb',
    authDomain: 'petcare-3f9cb.firebaseapp.com',
    storageBucket: 'petcare-3f9cb.firebasestorage.app',
  );

}