// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rx-fkietnl6ujCCwDP5Dn-P-JYPP22Q',
    appId: '1:472615681556:web:dd175fccdd164688ff3101',
    messagingSenderId: '472615681556',
    projectId: 'petcare-7f18d',
    authDomain: 'petcare-7f18d.firebaseapp.com',
    storageBucket: 'petcare-7f18d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi0GAo4ceOeBVTeT9BpScPdepXLR6aY04',
    appId: '1:472615681556:android:a8bc91a52f8f9c62ff3101',
    messagingSenderId: '472615681556',
    projectId: 'petcare-7f18d',
    storageBucket: 'petcare-7f18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWtQOjcfsRu3UqDP1i134ytbp539iFAc8',
    appId: '1:472615681556:ios:b9224fafb85ee3dbff3101',
    messagingSenderId: '472615681556',
    projectId: 'petcare-7f18d',
    storageBucket: 'petcare-7f18d.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );
}
